steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-west1-docker.pkg.dev/microservices-449514/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-west1-docker.pkg.dev/microservices-449514/image-registry/orders-ms',
    ]
serviceAccount: "projects/microservices-449514/serviceAccounts/cloud-build@microservices-449514.iam.gserviceaccount.com"
availableSecrets:
  secretManager:
  - versionName: projects/377384362022/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY  # Alternativamente puedes usar NONE o definir un logsBucket
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # Para que use un bucket regional automáticamente
  